apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: 30080
    # ДОБАВЬТЕ ЭТОТ БЛОК:
    - name: metrics
      port: 8081
      targetPort: 8081
