name: C/C++ CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make g++
      - name: Build script
        run: ./cicd/build.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-binaries
          path: usr/bin/
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: ./cicd/test.sh
  package:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download build artifacts
        uses: actions/download-artifact@v4
      - name: Install packaging tools
        run: sudo apt-get install -y dpkg-dev
      - name: Create .deb package
        run: ./cicd/package.sh
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: programm_1,0_all.deb
  deploy:
    runs-on: self-hosted
    needs: package 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy Dockerfile to build context
        run: |
          mkdir -p ./docker-context
          cp Dockerfile ./docker-context/
          cp dist/programm_1.0_all.deb ./docker-context/
      - name: Build Docker image
        run: |
          docker build -t my-program2:latest -f ./docker-context/Dockerfile ./docker-context
      - name: Test Docker container
        run: |
          docker run --rm my-program2:latest || {
            echo "Docker container failed to run successfully";
            exit 1;
          }
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag Docker image
        run: |
          docker tag my-program2 ${{ secrets.DOCKERHUB_USERNAME }}/my-program2:latest
      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-program2:latest
